#configtree: filename is key content is key
spring:
  config:
    import: optional:configtree:D:/learn/webapp/SpringBootProject/src/main/resources/etc/config/
  application:
    name: SpringBootProject
  #i18n配置
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false #没有默认值

my:
  service:
    enabled: false
    remote-address: 127.0.0.1
    security:
      username: hang
      password: 123321
      roles:
        - stu
        - tea


--- #multi-document syntax
spring:
  application:
    name: SpringBootProject1
  config:
    activate:
      # only active when running on Kubernetes, and only when either the dev or uat profiles are active
      on-profile: dev | uat
      on-cloud-platform: none
